title: "Zuah Han"
description: "Data Visualization | Portfolio + Daily Study Notes"
url: "https://zuahh.github.io"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
paginate: 5
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author:
  name: "Zuah Han"
  avatar: "/assets/img/avatar.png"
  bio: "University of Washington Data Visualization major interested in BI, Data Analysis, and GIS."
